config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  resources :users, only: %i[new create]
  resources :password_resets, only: %i[new create edit update]
  resource :profile, only: %i[show edit update]
  resources :user_sessions, only: [:new, :create, :destroy]

  resources :shops do
    resources :comments, only: %i[create edit destroy], shallow: true
    collection do
      get :search
    end
  end

  get 'products/index'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 65_535 }
  belongs_to :user
  belongs_to :shop
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["address", "category", "created_at", "description", "hot_rank", "id", "id_value", "img", "name", "rating", "updated_at"]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  authenticates_with_sorcery!
  # mount_uploader :avatar, AvatarUploader

  has_many :comments, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  # validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  # validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  # validates :reset_password_token, uniqueness: true, allow_nil: true

  # validates :first_name, presence: true, length: { maximum: 255 }
  # validates :last_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true
  validates :email, uniqueness: true



  def own?(object)
    id == object&.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :danger

  # def current_user
  #   @current_user ||= User.find_by(email: session[:email])
  # end
  # helper_method :current_user

  private

  def not_authenticated
    redirect_to login_path, danger: t('defaults.flash_message.require_login')
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # @comment = current_user.comments.build(comment_params)
    # @comment.save
    @shop = Shop.find(params[:shop_id])  # 投稿先の店舗を見つける
    @comment = @shop.comments.new(comment_params)  # 新しいコメントを店舗に関連付ける

    if @comment.save
      redirect_to @shop, notice: 'コメントが投稿されました！'
    else
      render 'shops/show'  # エラー時は店舗の詳細ページを再表示
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    # params.require(:comment).permit(:content).merge(user_id: params[:shop_id])
    params.require(:comment).permit(:content, :hot_rank).merge(user_id: current_user.id)  # ユーザーIDも追加
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
end

app/controllers/logouts_controller.rb
class LogoutsController < ApplicationController
  def show
    session.delete(:user_id)
    redirect_to root_url
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: t('defaults.flash_message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.flash_message.not_updated', item: User.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def show; end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email, :last_name, :first_name, :avatar, :avater_cashe)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]
  # before_action :set_q, only: %i[ index search ]
  before_action :set_q, only: [:index, :search]

  # GET /shops or /shops.json
  def index
    # @shops = Shop.all
    @q = Shop.ransack(params[:q])
    # @shops = @q.result(distinct: true).includes(:shop).order(created_at: :desc)
    @shops = @q.result(distinct: true)
  end

  # GET /shops/1 or /shops/1.json
  def show
    @shop = Shop.find(params[:id])
    @comment = Comment.new
    @comments = @shop.comments.includes(:user).order(created_at: :desc)
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully created." }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully updated." }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy!

    respond_to do |format|
      format.html { redirect_to shops_url, notice: "Shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # def search
  #   @results = @q.result
  # end

  def search
    @results = @q.result
  end

  private

  def set_q
    @q = Shop.ransack(params[:q])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_shop
    @shop = Shop.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def shop_params
    params.require(:shop).permit(:name, :address, :description, :rating, :hot_rank, :img, :category, :update_at)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login
  def top; end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end
  

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to shops_path, success: t('user_sessions.create.success')
    else
      flash.now[:danger] = t('user_sessions.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, danger: t('user_sessions.destroy.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('users.create.success')
    else
      flash.now[:danger] = t('users.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/logouts_helper.rb
module LogoutsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<tr id="comment-<%= comment.id %>">
  <td style="width: 60px">
    <%= image_tag "sample", width: "50", height: "50", class: "rounded-circle" %>
  </td>
  <td>
    <h3 class="small"><%= comment.user.decorate.name %></h3>
    <p><%= simple_format(comment.content) %></p>
  </td>
  <% if current_user.own?(comment) %>
    <td class="action">
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to "#", class: "edit-comment-link" do %>
            <i class="bi bi-pencil-fill"></i>
          <% end %>
        </li>
        <li class="list-inline-item">
          <%= link_to "#", class: "delete-comment-link" do %>
            <i class="bi bi-trash-fill"></i>
          <% end %>
        </li>
      </ul>
    </td>
  <% end %>
</tr>

app/views/comments/_form.html.erb
<div class="row mb-3" id="comment-form">
  <div class="col-lg-8 offset-lg-2">
  <%= form_with(model: [ @shop, Comment.new ]) do |form| %>
    <div>
      <%= form.label :content, "コメント" %>
      <%= form.text_area :content, required: true %>
    </div>
    <div>
      <%= form.label :hot_rank, "辛さ評価" %>
      <%= form.number_field :hot_rank, min: 1, max: 5, required: true %>
    </div>
    <div>※辛さは1〜5の間で入力ができます</div>
    <div>
      <%= form.submit "投稿する" %>
    </div>
  <% end %>
  </div>
</div>

app/views/comments/create.turbo_stream.erb
<% if @comment.errors.present? %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: @comment, shop: @comment.shop %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "table-comment" do %>
    <%= render 'comments/comment', comment: @comment %>
  <% end %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: Comment.new, shop: @comment.shop %>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment-#{@comment.id}" do %>
<% end %>

app/views/shops/_form.html.erb
<%= form_with(model: shop, class: "contents") do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :rating %>
    <%= form.text_field :rating, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :hot_rank %>
    <%= form.text_field :hot_rank, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :img %>
    <%= form.text_field :img, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category %>
    <%= form.text_field :category, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit :submit %>
  </div>
<% end %>

app/views/shops/_shop.html.erb
<div id="<%= dom_id shop %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= shop.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= shop.address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= shop.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Rating:</strong>
    <%= shop.rating %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Hot rank:</strong>
    <%= shop.hot_rank %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Img:</strong>
    <%= shop.img %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= shop.category %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Update at:</strong>
    <%= shop.update_at %>
  </p>

</div>

app/views/shops/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing shop</h1>

  <%= render "form", shop: @shop %>

  <%= link_to "Show this shop", @shop, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to shops", shops_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/shops/index.html.erb
<div class="wrapper">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Shops" %>

  <div id="shops" class="contener">
    <div class="img_box">
      <%= image_tag "top_img1.png" %>
    </div>

    <%= search_form_for @q, class: "search-form-7", url: search_shops_path do |f| %>
      <%= f.search_field :name_cont %>
      <%= f.submit '検索' %>
    <% end %>
    <h1 class="font-bold text-4xl">お店一覧</h1>
    <div class="flex justify-between items-center">
    <%= link_to "お店の新規登録", new_shop_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
    <ul>
      <% @shops.each do |shop| %>
        <li><%= shop.name %> - <%= link_to "お店情報", shop, class:"shop_link" %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shops/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New shop</h1>

  <%= render "form", shop: @shop %>

  <%= link_to "Back to shops", shops_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/shops/search.html.erb
<h1>検索結果</h1>
  <table class="contener">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Description</th>
        <th>Rating</th>
        <th>Hot_rank</th>
        <th>Category</th>
        <th>Link</th>
        <th>Link</th>
      </tr>
    </thead>

    <tbody>
      <% @results.each do |shop| %>
        <tr>
          <td><%= shop.name %></td>
          <td><%= shop.address %></td>
          <td><%= shop.description %></td>
          <td><%= shop.rating %></td>
          <td><%= shop.hot_rank %></td>
          <td><%= shop.category %></td>
          <td><%= link_to "Show", shop %></td>
          <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/shops/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @shop %>

    <%= link_to "お店の編集", edit_shop_path(@shop), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "お店一覧に戻る", shops_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "一覧から削除する", @shop, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>
<%= render 'comments/form', comment: @comment,shop: @shop %>
<div class="comment_box">
<p>コメント一覧</p>
  <div class="col-lg-8 offset-lg-2">
    <table class="table">
      <tbody id="table-comment">
        <!-- コメントの一覧表示 -->
        <% @shop.comments.each do |comment| %>
          <p>辛さ：<%= comment.hot_rank %> - コメント：<%= comment.content %> - ユーザー：<%= comment.user.name %></p>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<% content_for(:title, t('.title')) %>
<div class='container'>
  <div class='row'>
    <div class='col-md-10 col-lg-8 mx-auto'>
      <h1>ユーザー登録</h1>
      <%= form_with model: @user do |f| %>
        <div class='form-group'>
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit '登録', class: 'btn btn-primary' %>
      <% end %>
      <div class='text-center'>
        <%= link_to 'ログインページへ', login_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>プロフィール</h1>

<h3>ユーザー名</h3>
<%= @user.name %>
<h3>メールアドレス</h3>
<%= @user.email %>
<h3>プロフィール</h3>