config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  resources :users, only: %i[new create]
  resources :password_resets, only: %i[new create edit update]
  resource :profile, only: %i[show edit update]
  resources :user_sessions, only: [:new, :create, :destroy]

  resources :shops do
    resources :comments, only: %i[create edit destroy], shallow: true
    collection do
      get :search
    end
  end

  get 'products/index'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 65_535 }
  belongs_to :user
  belongs_to :shop
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["address", "category", "created_at", "description", "hot_rank", "id", "id_value", "img", "name", "rating", "updated_at"]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  authenticates_with_sorcery!
  # mount_uploader :avatar, AvatarUploader

  has_many :comments, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  # validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  # validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  # validates :reset_password_token, uniqueness: true, allow_nil: true

  # validates :first_name, presence: true, length: { maximum: 255 }
  # validates :last_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true
  validates :email, uniqueness: true



  def own?(object)
    id == object&.user_id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # @comment = current_user.comments.build(comment_params)
    # @comment.save
    @shop = Shop.find(params[:shop_id])  # 投稿先の店舗を見つける
    @comment = @shop.comments.new(comment_params)  # 新しいコメントを店舗に関連付ける

    if @comment.save
      redirect_to @shop, notice: 'コメントが投稿されました！'
    else
      render 'shops/show'  # エラー時は店舗の詳細ページを再表示
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    # params.require(:comment).permit(:content).merge(user_id: params[:shop_id])
    params.require(:comment).permit(:content, :hot_rank).merge(user_id: current_user.id)  # ユーザーIDも追加
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
end

app/controllers/logouts_controller.rb
class LogoutsController < ApplicationController
  def show
    session.delete(:user_id)
    redirect_to root_url
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: t('defaults.flash_message.updated', item: User.model_name.human)
    else
      flash.now['danger'] = t('defaults.flash_message.not_updated', item: User.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def show; end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:email, :last_name, :first_name, :avatar, :avater_cashe)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]
  # before_action :set_q, only: %i[ index search ]
  before_action :set_q, only: [:index, :search]

  # GET /shops or /shops.json
  def index
    # @shops = Shop.all
    @q = Shop.ransack(params[:q])
    # @shops = @q.result(distinct: true).includes(:shop).order(created_at: :desc)
    @shops = @q.result(distinct: true)
  end

  # GET /shops/1 or /shops/1.json
  def show
    @shop = Shop.find(params[:id])
    @comment = Comment.new
    @comments = @shop.comments.includes(:user).order(created_at: :desc)
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully created." }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully updated." }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy!

    respond_to do |format|
      format.html { redirect_to shops_url, notice: "Shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # def search
  #   @results = @q.result
  # end

  def search
    @results = @q.result
  end

  private

  def set_q
    @q = Shop.ransack(params[:q])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_shop
    @shop = Shop.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def shop_params
    params.require(:shop).permit(:name, :address, :description, :rating, :hot_rank, :img, :category, :update_at)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('users.create.success')
    else
      flash.now[:danger] = t('users.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/logouts_helper.rb
module LogoutsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "カレー検索アプリ" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
    
  <div class="container-fluid">
    <div class="contener">
      <% if logged_in? %>
        <%= render 'shared/header' %>
      <% else %>
        <%= render 'shared/before_login_header' %>
      <% end %>
      <%= render 'shared/flash_message' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </div>

  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="header_content navbar navbar-expand-lg navigation navbar-light bg-light">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='header_menu'>
        <li>
          <%= link_to 'ログイン', login_path ,class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
<div class="footer_content">
<div class="footer_content_item">
  <div><a href="#">お問い合わせ</a></div>
  <div><a href="#">利用規約</a></div>
  <div><a href="#">プライバシーポリシー</a></div>
</div>
</div>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p>Copyright © 2024. portfolio01</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='header_content navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to '/', class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>
    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <!-- link_toを使う形に修正してくださいdata属性、area属性の書き方は次の通りです。-->
      <!-- data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true' }, aria: { expanded: 'false' } -->
      <div class='dropdown-menu dropdown-menu-end'>
        <div class='header_menu_contenar'>
          <ul class='header_menu'>
          <li>
            <%= link_to 'プロフィール', profile_path, class: 'dropdown-item' %>
          </li>
          <li>
            <%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete }, class: 'dropdown-item' %>
          </li>
          <li>
            <%= link_to '検索', shops_path %>
          </li>
        </div>
      </div>
    </div>
  </nav>
</header>